[service]
name = "amelia"
build = "/"
repository = "https://github.com/Amelia-chan/Amelia"
restart_policy = { name = "always" }
override = true

[environment]
baseline = ".env"
override = false
server-side = false