name: "Build & Release"

on:
  push:
    branches: ['master']

jobs:
  release:
    name: "Build & Release"
    if: "contains(github.event.head_commit.message, '[RELEASE]')"
    runs-on: "ubuntu-latest"

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          
      - name: Setup Java
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
          
      - name: Set outputs
        id: vars
        run: echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"
        
      - name: Build with Maven
        run: |
            mvn clean verify assembly:single
            echo 'Amelia version successfully created.'
      - uses: "marvinpinto/action-automatic-releases@latest"
        id: releaser
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "amelia-build-${{ steps.vars.outputs.sha_short }}"
          prerelease: true
          title: "Amelia - Build ${{ steps.vars.outputs.sha_short }}"
          files: |
            target/*.jar
